name: Project code check with flake8

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Installing poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Installing project dependencies
        run: |
          make install
      - name: Pre-commit hooks
        run: |
          pip install pre-commit
          make pre-commit-check
